export const securityQuestions = [
  "What was the name of your first pet?",
  "What city were you born in?",
  "What was the make of your first car?",
  "What was the name of your elementary school?",
  "What was your childhood nickname?",
  "What is the middle name of your oldest sibling?",
  "What street did you grow up on?",
  "What was the name of your first teacher?",
  "What was your favorite childhood book?",
  "What was the name of your first employer?",
  "What city did your parents meet in?",
  "What was your favorite childhood food?",
  "What was the name of your first sports team?",
  "What was the model of your first mobile phone?",
  "What was the name of your childhood best friend?",
  "What was the first concert you attended?",
  "What was your favorite subject in school?",
  "What was the name of the hospital where you were born?",
  "What was your first job title?",
  "What is the name of a memorable childhood vacation place?",
];
